---
title: "``r read.dcf('../DESCRIPTION', fields = 'Package')[1]``: Getting Started" 
author: "<h4>Author: <i>Brian M. Schilder</i></h4>" 
date: "<h4>Updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  BiocStyle::html_document
vignette: >
    %\VignetteIndexEntry{echodata} 
    %\usepackage[utf8]{inputenc}
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup}
library(echoconda) 
```


# Examples  

## Build env from yaml

Will build the "echoR" conda environment by default.

```{r}
conda_env <- echoconda::yaml_to_env("echoR")
```

## Export 

```{r}
yaml_path <- echoconda::env_to_yaml(conda_env = "echoR")
```


## Activate conda env

```{r}
echoconda::activate_env(conda_env = "echoR")
```

## Find package path 

```{r}
pkgs <- echoconda::find_packages(packages = c("dplyr","numpy","wget"),
                                 conda_env = "echoR")
print(pkgs)
```

## Find python path

```{r}
python <- echoconda::find_python_path(conda_env = "echoR")
print(python)
```


# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  

<br>

